spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:h2:mem:springmaster
    username: farid
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true


server:
  port: 8081
  error:
    include-message: always
